Non-interactive template updater
QubesOS/qubes-core-admin-linux pull request #103
Opened 2022-06-28 13:15 UTC by piotrbartman

A simple updater that uses the apt/dnf python packages or the direct cli command to update templates.

Implementing [#7443](https://github.com/QubesOS/qubes-issues/issues/7443)

2022-06-28 14:19 UTC, marmarek commented on qubesupdate/agent/entrypoint
> +        f.write("\ndeltarpm=False\n")
Can you move this to some drop-in directory, where each such extra function is a separate script? It will be easier to manage them.

2022-07-11 18:05 UTC, marmarek requested changes
(not full review yet)

2022-07-13 13:25 UTC, piotrbartman commented on qubesupdate/agent/entrypoint
> +        f.write("\ndeltarpm=False\n")
done

2022-07-13 13:25 UTC, piotrbartman commented on qubesupdate/agent/package_manager.py
> +            cmd = ["sudo",
you're right, I removed unnecessary `sudo`

2022-07-13 13:25 UTC, piotrbartman commented on qubesupdate/agent/package_manager.py
> +            cmd = ["sudo",
same

2022-07-13 13:26 UTC, piotrbartman commented on qubesupdate/qube_connection.py
> +        exit_code, stdout_lines = self._run_shell_command_in_qube(
done

2022-07-13 13:28 UTC, piotrbartman commented on qubesupdate/update_manager.py
> +        dest_agent = os.path.join(dest_dir, UpdateAgentManager.ENTRYPOINT)
I agree, I changed destination path to `/run/qubes-update` and logpath to `/var/log/qubes/qubes-update`, it's ok?

2022-07-13 13:38 UTC, marmarek commented on qubesupdate/update_manager.py
> +        dest_agent = os.path.join(dest_dir, UpdateAgentManager.ENTRYPOINT)
Yes, that sounds better.

2022-08-10 03:07 UTC, marmarek requested changes
"one line progress reporting" commit has definitely not one line commit message ;)

2022-08-10 03:09 UTC, marmarek commented
CI says:
```
16:49:52,827 [executor:docker:dcf3942dad] output: DEBUG: make: python3: Command not found
```
You need `BuildRequires: python3-devel` in the spec file.

2022-08-10 15:36 UTC, piotrbartman commented on vmupdate/agent/source/apt/apt_api.py
> +                ).mkdir(parents=True, exist_ok=True)
`apt` creates it whenever it is needed, but the python package `apt` raises an error, so we need this to have  the same behavior in both cases. Generally, this is not a case, but this directory doesn't exist in a freshly installed template. Duplication is obviously a mistake so I fixed it.

2022-08-10 22:35 UTC, marmarek requested changes

2022-08-10 22:35 UTC, marmarek commented on vmupdate/qube_connection.py
> +            p1 = Popen(read_src, stdout=subprocess.PIPE)
You don't need `cat` for reading file from dom0. You can simply open it:
```python
with open(src, 'rb') as f:
    p2 = Popen(command, stdin=f)
    ...
```

2022-08-10 22:35 UTC, marmarek commented on vmupdate/qube_connection.py
> +            p.stdin.write((" ".join(command) + "\n").encode())
writing command here is not necessary anymore - you already sent it the line above

2022-08-16 15:30 UTC, marmarek commented on vmupdate/qube_connection.py
> +            "run command: %s", src, " ".join(command))
format string doesn't match actual arguments

2022-08-24 02:18 UTC, marmarek approved these changes
This looks okay now :)

I've run a few test manually, and looks good, but I'll give it a spin on openQA, which will test it on few more templates.

2022-08-25 14:41 UTC, marmarek commented
> * VmUpdates_debian-11: [test_121_updates_available_notification_qubes_vm_update_cli](https://openqa.qubes-os.org/tests/45879#step/VmUpdates_debian-11/7) (error)
>       `subprocess.CalledProcessError: Command '/usr/lib/qubes/upgrades-sta...`

This failure probably is about bug in upgrades-status-notify script, not update tool itself. Other failures looks unrelated. In other words - all good :)

2022-08-25 14:45 UTC, merged