Run commands locally if not showing remote output
QubesOS/qubes-core-admin-linux pull request #70
Opened 2021-01-04 22:30 UTC by DemiMarie

Salt parses the stdout of the command.  Therefore, if we are not showing
the remote command’s stdout, we need to run the command locally too.

2021-01-07 13:51 UTC, marmarek requested changes
As discussed elsewhere, this won't work. `list` or `search` actions do not download any packages, so nothing is sent back to dom0 - running command list/search in dom0 won't include results from remote repositories.
For interactive case, this is minor issue, since user can see the result in `xterm` spawned in UpdateVM (but there is a catch: it will close quickly after displaying results).
For non-GUI case (including salt), currently it needs extra `--show-output` option for search or list to make any sense (otherwise it will do the action but discard results). Maybe `REMOTE_ONLY=1` should imply `SHOW_OUTPUT=1` (if `CONSOLE=1`)?

2021-01-07 22:41 UTC, DemiMarie commented
Good idea!  The output is still sanitized by `qvm-run`, and (in the GUI case only) I can prevent the `xterm` from closing immediately.

2021-01-18 04:51 UTC, marmarek requested changes
This is rather to previous a PR, but I've found it only now: 
- don't call `exec script ...` - it confuses `script` as it "inherits" children of the original shell then, which makes `script` enter endless loop instead of exiting when the actual command ends

2021-01-21 11:17 UTC, DemiMarie commented on dom0-updates/qubes-dom0-update
> +exit "$status"'"' sh $CMD"
Done, thanks!

2021-01-24 03:32 UTC, marmarek commented
This still requires some changes on salt side (adding `--console --show-output` explicitly when needed and stripping coloring before parsing), but that's fine - I'll add appropriate version dependencies.

2021-01-24 03:32 UTC, marmarek approved these changes

2021-01-24 04:52 UTC, merged