Minor improvements to qubes-dom0-update
QubesOS/qubes-core-admin-linux pull request #91
Opened 2022-04-04 19:15 UTC by DemiMarie

This uses bash regex matching instead of the `echo | grep` anti-pattern,
replaces an `==` with `=`, adds a missing `--`, and unsets a variable
that will be checked for being set later.  It also replaces some uses of
`[` with `[[`.

The same approach used here could be used to refactor
qubes-gpg-client-wrapper if it were worth the time, which it probably
isn’t unless qubes-gpg-client-wrapper will see future use.

2022-12-11 04:32 UTC, marmarek requested changes
In it current shape, this PR makes `qubes-dom0-update` not functioning at all...

2022-12-11 04:32 UTC, marmarek commented on dom0-updates/qubes-dom0-update
> +set -euo pipefail
Both `set -e` and `set -o pipefail` breaks this in several ways. At the very least, there are several places that operate on `$?` to handle various exit codes (not only errors) - with `set -e` all that will stop working. But then, there is `tar` call that is supposed to pack files on best-effort basis (not all those files may be present on every system) - pipefail breaks this.

2022-12-13 06:38 UTC, marmarek requested changes

2022-12-13 06:38 UTC, marmarek commented on dom0-updates/qubes-dom0-update
> -(cd / && exec tar -c -- var/lib/rpm etc/yum/vars etc/yum.repos.d etc/yum.conf etc/dnf/dnf.conf etc/pki/rpm-gpg/RPM-GPG-KEY-* 2>/dev/null) |
You are reverting 37be9fbe610c67069ad4e59b595cc56a51da0514, I don't think it stopped being relevant (even if default install doesn't use it).

2022-12-20 15:55 UTC, marmarek requested changes

2022-12-20 15:55 UTC, marmarek commented on dom0-updates/qubes-dom0-update
> +dnf_conf=(var/lib/rpm etc/yum.repos.d etc/dnf/dnf.conf etc/pki/rpm-gpg/RPM-GPG-KEY-*)
This now fails because `etc/pki/rpm-gpg/RPM-GPG-KEY-*` isn't getting expanded.

2022-12-20 15:56 UTC, marmarek commented on dom0-updates/qubes-dom0-update
> +dnf_conf=(var/lib/rpm etc/yum.repos.d etc/dnf/dnf.conf etc/pki/rpm-gpg/RPM-GPG-KEY-*)
Maybe include the whole dir?

2022-12-25 10:27 UTC, marmarek commented
I don't see specific error, but something is still broken - packages are not downloaded (or not found at all): https://openqa.qubes-os.org/tests/56662#step/switch_pool/15

2022-12-30 09:05 UTC, DemiMarie commented
> I don't see specific error, but something is still broken - packages are not downloaded (or not found at all): https://openqa.qubes-os.org/tests/56662#step/switch_pool/15

That is weird; I will deal with it later.

2023-02-28 13:57 UTC, marmarek commented
This already conflicts, and will conflict even more after merging https://github.com/QubesOS/qubes-core-admin-linux/pull/116. Closing for now. _If_ you are interested in working on it, please rebase (after #116 gets merged), make it actually work, and reopen.

2023-02-28 13:57 UTC, closed without merging